### ISSUE TITLE
Нужна помощь со стратегией

### ISSUE THREAD

**Issue by Liddel2019** [EIDiamond/trade_backtesting#1]
Здраствуйте, я к сожалению еще не знаю python на достаточно хорошем уровне и поэтому прошу помощи. У меня есть стратегия из другого бота - [IntervalStrategy](https://github.com/qwertyo1/tinkoff-trading-bot/blob/develop/app/strategies/interval/IntervalStrategy.py) (https://github.com/qwertyo1/tinkoff-trading-bot). Если кому не сложно, можете помочь с тем чтобы изменить код так что бы это заработало. Могу дать на чай рублей 300. Заранее спасибо за ответ. Мой тг @liddel_off

**Comment by EIDiamond** [comment]
Duplicate #https://github.com/EIDiamond/invest-bot/issues/5

**Comment by EIDiamond** [comment]
Duplicate #https://github.com/EIDiamond/invest-bot/issues/5
