### ISSUE TITLE
Где я допустил ошибку?

### ISSUE THREAD

**Issue by Liddel2019** [EIDiamond/trade_backtesting#4]
я решил написать macd стратегию, но код перестал нормально работать. проект немного изменил под себя что бы тестирования походили в автоматическом режиме, но с вашими стратегиями все ок. В чем может быть проблемма?

[MacdStrategy.txt](https://github.com/EIDiamond/trade_backtesting/files/14341652/MacdStrategy.txt)
python 3.11
https://drive.google.com/file/d/1MsP3gbACyl4r_BAfRkMNfh-WwxDiO6QB/view?usp=sharing
буду очень признателен если поможете
E:\pythonProject\venv\Scripts\python.exe "C:/Program Files/JetBrains/PyCharm Community Edition 2023.2.1/plugins/python-ce/helpers/pydev/pydevd.py" --multiprocess --qt-support=auto --client 127.0.0.1 --port 30232 --file E:\pythonProject\main.py 
Connected to pydev debugger (build 232.9559.58)
1 из 431
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2023.2.1\plugins\python-ce\helpers\pydev\pydevd.py", line 1500, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2023.2.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:\pythonProject\main.py", line 196, in <module>
    result = test(config, commission_calculator, from_days, candles, auto=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonProject\main.py", line 48, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonProject\main.py", line 113, in test
    return HistoryTestsManager(trading_emulators, result_viewers, commission_calculator).test(from_days=from_days)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonProject\history_tests\history_manager.py", line 73, in test
    "AVG Profit": mean(summaries),
                  ^^^^^^^^^^^^^^^
  File "D:\python 3.11.8\Lib\statistics.py", line 432, in mean
    raise StatisticsError('mean requires at least one data point')
statistics.StatisticsError: mean requires at least one data point

Process finished with exit code 1

**Comment by EIDiamond** [comment]
Привет, я думаю основная теория такая:

File "E:\pythonProject\history_tests\history_manager.py", line 73
` additional_info = {
            "Summaries": summaries,
            "AVG Profit": mean(summaries),
            "Max Profit": max(summaries),
            "Min Profit": min(summaries),
        }
`
А именно: 
`"AVG Profit": mean(summaries),`

summaries - пустой список. Там нет ничего. Почему такое возможно?

тот же файл, 69 строка 
`summaries.append(profit - total_commission)` 
Ни разу не отработало добавление. Наверно потому что не было ни одного сигнала (тестового ордера) или типо того, зависит от данных уже. 
Смотри в эту сторону.

**Comment by Liddel2019** [comment]
хорошо спасибо!

**Comment by Liddel2019** [comment]
все вроде бы запустилось, последний вопрос как делать тестирования параллельно, куда изменения вносить?

**Comment by EIDiamond** [comment]
С параллельной работой сложности в Python, можно рассмотреть asyncio framework, но думаю для таких вычислений он существенного выигрыша не даст. 
Для данной задачи можно конечно уйти в докеры и все такое. Но возможно это будет сложно. 

Самое простое можно сделать несколько копий проекта в разных папках и запускать их независимо как разные проекты, код обновлять через git репозиторий.

**Comment by Liddel2019** [comment]
Спасибо за ответ!
